// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEkij9cv3puxXeNhnWWH6W9Bw_TpOOtSQ',
    appId: '1:434424161446:web:e352c04ef1626b150b0067',
    messagingSenderId: '434424161446',
    projectId: 'meal-monkey-app-36791',
    authDomain: 'meal-monkey-app-36791.firebaseapp.com',
    storageBucket: 'meal-monkey-app-36791.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKq5S8TeS_l8-kP2AJi4QxAw9B7ij2xQg',
    appId: '1:434424161446:android:25784f762d09c7440b0067',
    messagingSenderId: '434424161446',
    projectId: 'meal-monkey-app-36791',
    storageBucket: 'meal-monkey-app-36791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcO8RCQ_wngZyGcWdhgqIIea5d0jii-0',
    appId: '1:434424161446:ios:38b276d14f27ea7f0b0067',
    messagingSenderId: '434424161446',
    projectId: 'meal-monkey-app-36791',
    storageBucket: 'meal-monkey-app-36791.appspot.com',
    iosClientId:
        '434424161446-g26r32mejdk3md1sacahh501oefdnmki.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealMonkeyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcO8RCQ_wngZyGcWdhgqIIea5d0jii-0',
    appId: '1:434424161446:ios:f253a199006171030b0067',
    messagingSenderId: '434424161446',
    projectId: 'meal-monkey-app-36791',
    storageBucket: 'meal-monkey-app-36791.appspot.com',
    iosClientId:
        '434424161446-f5caj2r6qo6uoi89tofh3r7c619coqol.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealMonkeyApp.RunnerTests',
  );
}
